import { getCollection } from 'astro:content';

/** Get all topics sorted by display order */
export async function getAllTopics() {
  const topics = await getCollection('topics');
  return topics.sort((a, b) => a.data.order - b.data.order);
}

/** Get a single topic by its slug */
export async function getTopicBySlug(slug: string) {
  const topics = await getCollection('topics');
  return topics.find((t) => t.data.slug === slug);
}

/** Get all non-draft FAQs for a topic, sorted by order */
export async function getFaqsByTopic(topicSlug: string) {
  const faqs = await getCollection('faqs');
  return faqs
    .filter((f) => f.data.topic === topicSlug && !f.data.draft)
    .sort((a, b) => a.data.order - b.data.order);
}

/** Get all non-draft videos for a topic, sorted by order */
export async function getVideosByTopic(topicSlug: string) {
  const videos = await getCollection('videos');
  return videos
    .filter((v) => v.data.topic === topicSlug && !v.data.draft)
    .sort((a, b) => a.data.order - b.data.order);
}

/**
 * Resolve an array of content IDs to their full entries.
 * IDs are in the format "topic/slug" as generated by the glob loader.
 */
export async function resolveRelatedFAQs(ids: string[]) {
  if (!ids.length) return [];
  const all = await getCollection('faqs');
  return all.filter((f) => ids.includes(f.id));
}

export async function resolveRelatedVideos(ids: string[]) {
  if (!ids.length) return [];
  const all = await getCollection('videos');
  return all.filter((v) => ids.includes(v.id));
}

/**
 * Extract the slug portion from a glob-generated content ID.
 * e.g., "education/right-to-education" → "right-to-education"
 */
export function getSlugFromId(id: string): string {
  const parts = id.split('/');
  return parts[parts.length - 1];
}

/**
 * Build the URL path for a content entry based on its type and data.
 */
export function getContentUrl(
  type: 'faq' | 'video',
  topic: string,
  id: string
): string {
  const slug = getSlugFromId(id);
  const typeSegment = type === 'video' ? 'videos' : 'faq';
  return `/topics/${topic}/${typeSegment}/${slug}/`;
}

/**
 * Check which resource types are available for a topic.
 */
export async function getTopicResourceCounts(topicSlug: string) {
  const [faqs, videos, topic] = await Promise.all([
    getFaqsByTopic(topicSlug),
    getVideosByTopic(topicSlug),
    getTopicBySlug(topicSlug),
  ]);
  return {
    faqCount: faqs.length,
    videoCount: videos.length,
    hasSyllabus: !!(topic?.data.guidedSyllabus),
    hasFAQ: faqs.length > 0,
    hasVideo: videos.length > 0,
  };
}
